clear
clc


res=2;
dur=66;


all_trials.glm_dd=nan(dur/res,3495);
all_trials.glm_df=nan(dur/res,3495);
all_trials.glm_fd=nan(dur/res,3495);
all_trials.glm_ff=nan(dur/res,3495);
all_trials.glm_time=nan(length(-1:res/100:2),3495);
all_trials.glm_context=nan(length(-1:res/100:2),3495);
all_trials.glm_choice=nan(length(-1:res/100:2),3495);

bootstrap.glm_dd_se=nan(dur/res,3495);
bootstrap.glm_df_se=nan(dur/res,3495);
bootstrap.glm_fd_se=nan(dur/res,3495);
bootstrap.glm_ff_se=nan(dur/res,3495);
bootstrap.glm_time_se=nan(length(-1:res/100:2),3495);
bootstrap.glm_context_se=nan(length(-1:res/100:2),3495);
bootstrap.glm_choice_se=nan(length(-1:res/100:2),3495);

glm_dds=nan(5,33,3495);
glm_dfs=nan(5,33,3495);
glm_fds=nan(5,33,3495);
glm_ffs=nan(5,33,3495);


for z=1:3495
    

    load(['data/neural_kernels/filter_' num2str(z) '.mat'])
    %%% (generated by compute_all_kernels.m)



    all_trials.glm_dd(:,z)=glm_fit.kernels.dd;
    all_trials.glm_fd(:,z)=glm_fit.kernels.fd;
    all_trials.glm_df(:,z)=glm_fit.kernels.df;
    all_trials.glm_ff(:,z)=glm_fit.kernels.ff;
    all_trials.glm_time(:,z)=glm_fit.kernels.time;
    all_trials.glm_context(:,z)=glm_fit.kernels.context;
    all_trials.glm_choice(:,z)=glm_fit.kernels.choice;


    bootstrap.glm_dd_se(:,z)=glm_fit.bootstrap.dd_se;
    bootstrap.glm_fd_se(:,z)=glm_fit.bootstrap.fd_se;
    bootstrap.glm_df_se(:,z)=glm_fit.bootstrap.df_se;
    bootstrap.glm_ff_se(:,z)=glm_fit.bootstrap.ff_se;
    bootstrap.glm_time_se(:,z)=glm_fit.bootstrap.time_se;
    bootstrap.glm_context_se(:,z)=glm_fit.bootstrap.context_se;
    bootstrap.glm_choice_se(:,z)=glm_fit.bootstrap.choice_se;


    glm_dds(:,:,z)=glm_fit.bootstrap.dd;
    glm_fds(:,:,z)=glm_fit.bootstrap.fd;
    glm_dfs(:,:,z)=glm_fit.bootstrap.df;
    glm_ffs(:,:,z)=glm_fit.bootstrap.ff;


end



iii=1;

data_all_trials.glm_dd=all_trials.glm_dd(:,:,iii);
data_all_trials.glm_fd=all_trials.glm_fd(:,:,iii);
data_all_trials.glm_df=all_trials.glm_df(:,:,iii);
data_all_trials.glm_ff=all_trials.glm_ff(:,:,iii);
data_all_trials.glm_time=all_trials.glm_time(:,:,iii);
data_all_trials.glm_context=all_trials.glm_context(:,:,iii);
data_all_trials.glm_choice=all_trials.glm_choice(:,:,iii);



vecx=0.01:0.02:0.66;

save('data/combined_kernels.mat','vecx','data_all_trials','glm');




load data/rat_for_each_neuron

rat_names={'P049','P055','P059','P095','P100','P101','P102'};


for iii=1:length(rat_names)

    rat=rat_names{iii};

    rat=rat(2:end);
    rat=str2double(rat);

    ind_bootstrap=find(rat_numbers==rat);

    wddall_se=permute(glm_dds(:,:,ind_bootstrap),[2 3 1]);
    wdfall_se=permute(glm_dfs(:,:,ind_bootstrap),[2 3 1]);
    wfdall_se=permute(glm_fds(:,:,ind_bootstrap),[2 3 1]);
    wffall_se=permute(glm_ffs(:,:,ind_bootstrap),[2 3 1]);

    save(['data/kernel_bootstrap_' rat_names{iii} '.mat'],'wddall_se','wfdall_se','wdfall_se','wffall_se');

end











