clear
% clc


res=2;
dur=66;



all_trials_loc.glm_dd=nan(dur/res,3495);
all_trials_loc.glm_df=nan(dur/res,3495);
all_trials_loc.glm_fd=nan(dur/res,3495);
all_trials_loc.glm_ff=nan(dur/res,3495);
all_trials_loc.glm_time=nan(length(-1:res/100:2),3495);
all_trials_loc.glm_context=nan(length(-1:res/100:2),3495);
all_trials_loc.glm_choice=nan(length(-1:res/100:2),3495);


all_trials_freq.glm_dd=nan(dur/res,3495);
all_trials_freq.glm_df=nan(dur/res,3495);
all_trials_freq.glm_fd=nan(dur/res,3495);
all_trials_freq.glm_ff=nan(dur/res,3495);
all_trials_freq.glm_time=nan(length(-1:res/100:2),3495);
all_trials_freq.glm_context=nan(length(-1:res/100:2),3495);
all_trials_freq.glm_choice=nan(length(-1:res/100:2),3495);




for z=1:3495
    

    load(['data/neural_kernels_per_context/filter_' num2str(z) '.mat'])
    %%% (generated by compute_all_kernels_per_context.m)


    if(~isempty(glm_fit_loc))
        data_all_trials_loc.glm_dd(:,z)=glm_fit_loc.kernels.dd;
        data_all_trials_loc.glm_fd(:,z)=glm_fit_loc.kernels.fd;
        data_all_trials_loc.glm_df(:,z)=glm_fit_loc.kernels.df;
        data_all_trials_loc.glm_ff(:,z)=glm_fit_loc.kernels.ff;
        data_all_trials_loc.glm_time(:,z)=glm_fit_loc.kernels.time;
        data_all_trials_loc.glm_context(:,z)=glm_fit_loc.kernels.context;
        data_all_trials_loc.glm_choice(:,z)=glm_fit_loc.kernels.choice;
    end



    if(~isempty(glm_fit_freq))
        data_all_trials_freq.glm_dd(:,z)=glm_fit_freq.kernels.dd;
        data_all_trials_freq.glm_fd(:,z)=glm_fit_freq.kernels.fd;
        data_all_trials_freq.glm_df(:,z)=glm_fit_freq.kernels.df;
        data_all_trials_freq.glm_ff(:,z)=glm_fit_freq.kernels.ff;
        data_all_trials_freq.glm_time(:,z)=glm_fit_freq.kernels.time;
        data_all_trials_freq.glm_context(:,z)=glm_fit_freq.kernels.context;
        data_all_trials_freq.glm_choice(:,z)=glm_fit_freq.kernels.choice;
    end
    



end



vecx=0.01:0.02:0.66;

save('data/combined_kernels_per_context.mat','vecx',...
    'data_all_trials_loc','data_all_trials_freq','glm');

    

    


