clear
clc



%%% find rats with at least 100000 trials
%%% (generated by number_sessions_per_rat.m)
load('data/numsessions_all_rats.mat');
rat_list=rats(find(numhits>=100000));


for qqq=1:length(rat_list)
    
    ratto=rat_list{qqq};

    compute_logistic_regression(ratto);

end




