clear
clc
close all


%%% (generated by number_sessions_per_rat.m)
load data/numsessions_all_rats
rat_list=rats(find(numhits>=100000));


for iii=1:length(rat_list)
    
    ratto=rat_list{iii};
    
    [d_shap1(iii),f_shap1(iii)] = plot_logistic_regression(ratto,'half1','slope',0,0,0);
    [d_shap2(iii),f_shap2(iii)] = plot_logistic_regression(ratto,'half2','slope',0,0,0);
   
end


figure; 
hold on;
plot(d_shap1,d_shap2,'.k','MarkerSize',50);
plot(f_shap1,f_shap2,'.b','MarkerSize',50);
set(gca,'TickDir','out','FontSize',20);
box off;
xlabel('Index frequency');
ylabel('Index location')
axis equal


xlim([-1 0.37]);
ylim([-1 0.37]);


set(gca,'XTick',-1:.5:0);
set(gca,'YTick',-1:.5:0);


[val,pval]=corr([d_shap1';f_shap1'],[d_shap2';f_shap2'])



