clear
clc
close all


load data/taskswitch_all_rats
%%% (generated by save_taskswitch_all.m)


prevstart=5;
prevend=30;
lenprev=prevend-prevstart+1;
newend=30;

xvals=(1:lenprev+newend)-26.5;



figure; subplot(1,2,1); hold on
plot(xvals,az1d2f,'k-','LineWidth',1,'MarkerSize',30)
plot(xvals,az2d2f,'b-','LineWidth',1,'MarkerSize',30)
plot([0 0],[.2 .8],'k--','LineWidth',2)
title('direction to frequency')
xlim([-10 20])
xlabel('Trials from context switch')
ylabel('Relative weight')
set(gca,'TickDir','out','FontSize',24)
box off
ylim([.07 .93])
xlim([-3 6])
set(gca,'XTick',[0 5])
set(gca,'YTick',[.1 .5 .9])



subplot(1,2,2); hold on
plot(xvals,az1f2d,'k-','LineWidth',1,'MarkerSize',30)
plot(xvals,az2f2d,'b-','LineWidth',1,'MarkerSize',30)
plot([0 0],[.2 .8],'k--','LineWidth',2)
title('frequency to direction')
xlim([-10 20])
xlabel('Trials from context switch')
ylabel('Relative weight')
set(gca,'TickDir','out','FontSize',24)
box off
ylim([.07 .93])
xlim([-3 6])
set(gca,'XTick',[0 5])
set(gca,'YTick',[.1 .5 .9])







load data/taskswitch_all_rats
%%% (generated by save_taskswitch_all.m)



az1d2f=nanmean(az1d2f,2);
az2d2f=nanmean(az2d2f,2);
az1f2d=nanmean(az1f2d,2);
az2f2d=nanmean(az2f2d,2);



prevstart=5;
prevend=30;
lenprev=prevend-prevstart+1;
newend=30;




subplot(1,2,1); hold on
plot(xvals,az1d2f,'k.-','LineWidth',2,'MarkerSize',50)
plot(xvals,az2d2f,'b.-','LineWidth',2,'MarkerSize',50)
plot([0 0],[.2 .8],'k--','LineWidth',2)
title('direction to frequency')
xlim([-10 20])
xlabel('Trials from context switch')
ylabel('Relative weight')
set(gca,'TickDir','out','FontSize',24)
box off
ylim([.07 .93])
xlim([-3 6])
set(gca,'XTick',[0 5])
set(gca,'YTick',[.1 .5 .9])



subplot(1,2,2); hold on
plot(xvals,az1f2d,'k.-','LineWidth',2,'MarkerSize',50)
plot(xvals,az2f2d,'b.-','LineWidth',2,'MarkerSize',50)
plot([0 0],[.2 .8],'k--','LineWidth',2)
title('frequency to direction')
xlim([-10 20])
xlabel('Trials from context switch')
ylabel('Relative weight')
set(gca,'TickDir','out','FontSize',24)
box off
ylim([.07 .93])

xlim([-3 6])
set(gca,'XTick',[0 5])
set(gca,'YTick',[.1 .5 .9])


