clear
clc
close all

load data/training_all
%%% (generated by save_training_all.m)

be=(bdirs+bfreqs)/2;


%%% remove final sessions if performanes go below threshold
for i=1:size(be,1)
    ind=find(be(i,1:360)>.7);
    if(isempty(ind))
        be(i,:)=nan;
    else
        be(i,ind(end)+1:end)=nan;
    end
end


figure;
plot(1:360,be(:,1:360),'k')
hold on
plot(xlim,[.5 .5],'k--','LineWidth',3)
plot(xlim,[.7 .7],'r--','LineWidth',3)
xlim([1 360])
ylim([.45 1])

