clear
clc
close all


%script that plots behavior regression weights across all animals


%%% (generated by number_sessions_per_rat.m)
load data/numsessions_all_rats
rat_list=rats(find(numhits>=120000));



%%% load psychometrics data (generated by save_psychometrics.m)
load data/psychometrics_all_rats rats cdirs cfreqs cdir_nums cfreq_nums
rats_psychometrics=rats;


for iii=1:length(rat_list)
    
    ratto=rat_list{iii};
    
    [d_shap(iii),f_shap(iii)] = plot_logistic_regression(ratto,'all_trials','ratio',0,0,0);
   
end




%%% rats are plotted in order according to their score
[vald,indd]=sort(d_shap,'descend');
[valf,indf]=sort(f_shap,'descend');


    

%%%% PLOT KERNELS FOR LOCATION EVIDENCE %%%%



h_loc=figure;
set(h_loc,'Position',[437   400   1100   115]);

%%% this defines the subplots
ha_loc = tight_subplot(1,length(rat_list),0.01,0.02,0.02);

h_freq=figure;
set(h_freq,'Position',[437   200   1100   115]);

%%% this defines the subplots
ha_freq = tight_subplot(1,length(rat_list),0.01,0.02,0.02);




plot_errorbars=1;
plot_markers=0;


plot_type='difference';

for i=1:length(rat_list)
    
    %%% choose the index of the rat according to location score
    iii=indd(i);
    ratto=rat_list{iii};
    
    %%% choose correct location subplot
    axes(ha_loc(i));
    plot_logistic_regression(ratto,'all_trials','slope',1,'location',plot_type,plot_errorbars,plot_markers);

    
    
    %%% choose the index of the rat according to frequency score
    iii=indf(i);
    ratto=rat_list{iii};
    
    %%% choose correct frequency subplot
    axes(ha_freq(i));
    plot_logistic_regression(ratto,'all_trials','slope',1,'frequency',plot_type,plot_errorbars,plot_markers);
    
end













% plot_type='difference';
plot_type='original';

h_loc2=figure;
set(h_loc2,'Position',[437   400   1100   115]);

%%% this defines the subplots
ha_loc2 = tight_subplot(1,length(rat_list),0.01,0.02,0.02);

h_freq2=figure;
set(h_freq2,'Position',[437   200   1100   115]);

%%% this defines the subplots
ha_freq2 = tight_subplot(1,length(rat_list),0.01,0.02,0.02);




plot_errorbars=1;
plot_markers=0;


for i=1:length(rat_list)
    
    %%% choose the index of the rat according to location score
    iii=indd(i);
    ratto=rat_list{iii};
    
    %%% choose correct location subplot
    axes(ha_loc2(i));
    plot_logistic_regression(ratto,'all_trials','slope',1,'location',plot_type,plot_errorbars,plot_markers);

    
    
    %%% choose the index of the rat according to frequency score
    iii=indf(i);
    ratto=rat_list{iii};
    
    %%% choose correct frequency subplot
    axes(ha_freq2(i));
    plot_logistic_regression(ratto,'all_trials','slope',1,'frequency',plot_type,plot_errorbars,plot_markers);
    
end








h3=figure;
set(h3,'Position',[437   200   895   100]);

ha = tight_subplot(1,length(rat_list),0.01,0.01,0.01);
for i=1:length(rat_list)
    
    iii=indf(i);
    
    
    ratto=rat_list{iii};
    
    
    axes(ha(i));
    
    
    
    rat_index=find(ismember(rats_psychometrics,ratto));
    
    cdir=cdirs{rat_index};
    cfreq=cfreqs{rat_index};
    cdir_num=cdir_nums{rat_index};
    cfreq_num=cfreq_nums{rat_index};
    
    
    
%     
%     figure
    
    vec=[-4 -2.5 -1 1 2.5 4];
    
    le1=cdir;
    le2=cfreq;
    
    
    
    
    
    y2=nanmean(le1,2);
    plot(vec,y2,'.','MarkerSize',10,'Color',[0 1 1])
    ylim([0 1])
    xlim([-4 4])
    hold on
    plot([-4 4],[.5 .5],'k:','LineWidth',2)
    set(gca,'XTick',vec)
    
    box off
    set(gca,'TickDir','out')
    set(gca,'XTick',[],'YTick',[])

    
    
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y2, ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'Color',[0 1 1],'LineWidth',1)
    
    
    
    y4=nanmean(le2,2);
    plot(vec,y4,'b.','MarkerSize',10)
    ylim([0 1])
    xlim([-4 4])
    hold on
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    set(gca,'XTick',vec)
    
    box off
    set(gca,'TickDir','out')
    set(gca,'XTick',[],'YTick',[])
    
    
    
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y4, ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'b','LineWidth',1)
    


    
    
    
    
end







h4=figure;
set(h4,'Position',[437   200   895   100]);

ha = tight_subplot(1,length(rat_list),0.01,0.01,0.01);
for i=1:length(rat_list)
    
    iii=indd(i);
    
    
    ratto=rat_list{iii};
    
    
    axes(ha(i));
    
    
    
    rat_index=find(ismember(rats_psychometrics,ratto));
    
    cdir=cdirs{rat_index};
    cfreq=cfreqs{rat_index};
    cdir_num=cdir_nums{rat_index};
    cfreq_num=cfreq_nums{rat_index};
    
    

    
    vec=[-4 -2.5 -1 1 2.5 4];
    
    le1=cdir;
    le2=cfreq;
    

    y1=nanmean(le1,1);
    plot(vec,y1,'k.','MarkerSize',10)
    
    
    ylim([0 1])
    xlim([-4 4])
    hold on
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    set(gca,'XTick',vec)
    
    box off
    set(gca,'TickDir','out')
    set(gca,'XTick',[],'YTick',[])
    
    
    
    
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y1', ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'k','LineWidth',1)
    
    
    
    y3=nanmean(le2,1);
    plot(vec,y3,'.','MarkerSize',10,'Color',[0.6 0.6 0.6])
    ylim([0 1])
    xlim([-4 4])
    hold on
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    set(gca,'XTick',vec)
    
    box off
    set(gca,'TickDir','out')
    set(gca,'XTick',[],'YTick',[])
    
    
    
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y3', ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'Color',[0.6 0.6 0.6],'LineWidth',1)
    
    
    
    
    

    
    
end










