clear
clc
close all

%%% extended data fig 5 a-g

%%%% ext data figure that compares choice axis across rats



load('data/combined_kernels_per_context.mat')
%%% (generated by combine_neural_kernels_per_context.m)



data1=data_all_trials_loc;
data2=data_all_trials_freq;


resolution=glm.res*100;

data1.centers=-1:resolution/100:2;
data1.vecx=0.01:glm.res:glm.pulsedur;

data2.centers=-1:resolution/100:2;
data2.vecx=0.01:glm.res:glm.pulsedur;




wchall_all1=data1.glm_choice;
wchall_all2=data2.glm_choice;




if(0)
    %%% Control: If we look at the context kernels instead, they vary hugely
    %%% across rats, whereas the choice kernels are all qualitatively similar

    %use context kernels instead
    wchall_all1=data1.glm_context;
    wchall_all2=data2.glm_context;
end


wchall_all1=wchall_all1(51:end,:);
wchall_all2=wchall_all2(51:end,:);
data1.centers=data1.centers(51:end);
data2.centers=data2.centers(51:end);



%remove nans
good=find(~isnan(mean(wchall_all1,1)) & ~isnan(mean(wchall_all2,1)));
wchall_all1=wchall_all1(:,good);
wchall_all2=wchall_all2(:,good);




load data/rat_for_each_neuron


rat_numbers=rat_numbers(good);
ratnums=[100 59 95 49 101 102 55];

wchall_all1_save=wchall_all1;
wchall_all2_save=wchall_all2;


for iii=1:7

    wchall_all1=wchall_all1_save;
    wchall_all2=wchall_all2_save;

    wchall_all1=wchall_all1(:,rat_numbers==ratnums(iii));
    wchall_all2=wchall_all2(:,rat_numbers==ratnums(iii));




    cc_all1=pca(wchall_all1(1:66,:));
    cc_all1=cc_all1(:,1);
    cc_all2=pca(wchall_all2(1:66,:));
    cc_all2=cc_all2(:,1);



    %
    cor(iii)=abs(corr(cc_all1,cc_all2));

    vec1=cc_all1/norm(cc_all1);
    vec2=cc_all2/norm(cc_all2);


    ango(iii)=acos(vec1'*vec2)*180/pi;

    wchall_all1=wchall_all1/norm(wchall_all1);
    wchall_all2=wchall_all2/norm(wchall_all2);

    [cc_all,~,lat]=pca([wchall_all1; wchall_all2]);
    %     cc_all=cc_all(:,1:3);
    sc_all1=(wchall_all1-mean(wchall_all1))*cc_all;
    sc_all2=(wchall_all2-mean(wchall_all2))*cc_all;


    sc_all1=sc_all1-repmat(sc_all1(1,:),[101,1]);
    sc_all2=sc_all2-repmat(sc_all2(1,:),[101,1]);


    h=figure;
    set(h,'Position',[616   598   560   276]);
    subplot(1,2,1)

    hold on
    plot3(sc_all1(:,1),sc_all1(:,2),sc_all1(:,3),'-','LineWidth',2,'Color',[162 0 148]/255);

    plot3(-sc_all1(:,1),-sc_all1(:,2),-sc_all1(:,3),'-','LineWidth',2,'Color',[162 0 148]/255);


    plot3(sc_all1(1,1),sc_all1(1,2),sc_all1(1,3),'.','MarkerSize',20,'Color',[162 0 148]/255);

    plot3(sc_all1(66,1),sc_all1(66,2),sc_all1(66,3),'.','MarkerSize',20,'Color',[162 0 148]/255);
    plot3(-sc_all1(66,1),-sc_all1(66,2),-sc_all1(66,3),'.','MarkerSize',20,'Color',[162 0 148]/255);


    set(gca,'FontSize',20)
    set(gca,'XTick',[],'YTick',[]);
    xlabel('PC 1')
    ylabel('PC 2')


    box off
    set(gca,'TickDir','out')


    punto=cc_all1'*cc_all/5;
    plot3([-punto(1) punto(1)],[-punto(2) punto(2)],[-punto(3) punto(3)],'Color',[162 0 148]/255,'LineWidth',3);





    subplot(1,2,2)

    hold on
    plot3(sc_all2(:,1),sc_all2(:,2),sc_all2(:,3),'-','LineWidth',2,'Color',[162 0 148]/255);

    plot3(-sc_all2(:,1),-sc_all2(:,2),-sc_all2(:,3),'-','LineWidth',2,'Color',[162 0 148]/255);


    plot3(sc_all2(1,1),sc_all2(1,2),sc_all2(1,3),'.','MarkerSize',20,'Color',[162 0 148]/255);


    plot3(sc_all2(66,1),sc_all2(66,2),sc_all2(66,3),'.','MarkerSize',20,'Color',[162 0 148]/255);
    plot3(-sc_all2(66,1),-sc_all2(66,2),-sc_all2(66,3),'.','MarkerSize',20,'Color',[162 0 148]/255);


    set(gca,'FontSize',20)
    set(gca,'XTick',[],'YTick',[]);
    xlabel('PC 1')
    ylabel('PC 2')
    zlabel('Choice axis 3')

    box off
    set(gca,'TickDir','out')


    punto=cc_all2'*cc_all/5;
    plot3([-punto(1) punto(1)],[-punto(2) punto(2)],[-punto(3) punto(3)],'Color',[162 0 148]/255,'LineWidth',3);












    %%%% now compute stuff in the first 3 pc components

    var_eplained(iii)=sum(lat(1:3))/sum(lat);
    cc_all1=cc_all1/norm(cc_all1);
    cc_all1_reduced=cc_all1'*cc_all(:,1:3);
    cc_all2_reduced=cc_all2'*cc_all(:,1:3);


    vec1=cc_all1_reduced/norm(cc_all1_reduced);
    vec2=cc_all2_reduced/norm(cc_all2_reduced);


    ango(iii)=acos(vec1*vec2')*180/pi;
    if(ango(iii)>90)
        ango(iii)=180-ango(iii);
    end





end
figure;
hist(cor);
xlim([0 1])
xlabel('Correlation')
ylabel('N. of rats')
set(gca,'TickDir','out')
box off
set(gca,'FontSize',20)

figure;
hist(ango);
xlabel('angle between axes (degrees)')
ylabel('N. of rats')
set(gca,'TickDir','out')
box off
set(gca,'FontSize',20)
xlim([0 90])
set(gca,'XTick',[0 45 90])
set(gca,'YTick',[0 1 2]);








