clear
clc
close all

rat='P049';

rat=rat(2:end);
rat=str2double(rat);




load data/combined_kernels.mat
%%% (generated by combine_neural_kernels.m)



data=data_all_trials;

data.centers=-1:0.02:2;

vecx=0.01:0.02:0.66;
data.vecx=vecx;




load data/rat_for_each_neuron
ind=find(rat_numbers==rat);




wddall=data.glm_dd(:,ind);
wfdall=data.glm_fd(:,ind);
wdfall=data.glm_df(:,ind);
wffall=data.glm_ff(:,ind);
wchall=data.glm_choice(:,ind);



centers=data.centers;
vecx=data.vecx;

wchall_all=wchall;

[~,ind1]=min(abs(centers));
[~,ind2]=min(abs(centers-1.3));
indi=ind1:ind2;
wchall=wchall(indi,:);



[cc,sc,lc]=pca(wchall);


if(sign(wchall(end,:)*cc(:,1))<0)
    cc(:,1)=-cc(:,1);
end



wdall=(wddall+wdfall)/2;
wfall=(wfdall+wffall)/2;


[cd3,sd,ld]=pca(wdall);
[cf3,sf,lf]=pca(wfall);


d_ratio=norm(wdfall(end,:))/norm(wddall(end,:));

f_ratio=norm(wfdall(end,:))/norm(wffall(end,:));



wddall_orig=wddall;
wfdall_orig=wfdall;
wdfall_orig=wdfall;
wffall_orig=wffall;

wchall=[zeros(1,length(ind)); wchall];
wddall=[wddall;zeros(1,length(ind))];
wfdall=[wfdall;zeros(1,length(ind))];
wdfall=[wdfall;zeros(1,length(ind))];
wffall=[wffall;zeros(1,length(ind))];



d1=fliplr(cc(:,1)'*wddall_orig');
d2=fliplr(cc(:,1)'*wdfall_orig');

f1=fliplr(cc(:,1)'*wffall_orig');
f2=fliplr(cc(:,1)'*wfdall_orig');




x=vecx;
y=d1-d2;
y=y/max(abs(y));
pd=polyfit(x,y,1);
d_shap=pd(1);

x=vecx;
y=f1-f2;
y=y/max(abs(y));
pf=polyfit(x,y,1);
f_shap=pf(1);




c=[cc(:,1) cd3(:,1) cd3(:,2)];

num_neur=10;

[~,ind]=sort((c(:,1)),'descend');


figure


vec=wffall_orig-wfdall_orig;


subplot(2,2,1)
plot(vecx,flipud(vec(:,ind(1:num_neur))),'LineWidth',2)
hold on
plot(xlim,[0 0],'k--','LineWidth',2)

yli=ylim;

ylim([-.015 yli(2)]);
xlim([0 0.65])

xlabel('Time (s)')
set(gca,'Fontsize',20,'TickDir','out','YTick',[])
box off
title('Neurons, LOC')




subplot(2,2,3)
a=wffall_orig';
curve1=fliplr(c(:,1)'*a);
a=wfdall_orig';
curve2=fliplr(c(:,1)'*a);



difa=curve1-curve2;
maxval=max(abs(difa));
difa=difa/maxval;


hold on
plot(vecx,difa,'-','MarkerSize',10,'LineWidth',2,'Color',[0 0 0]/255)
plot(vecx(1:8:end),difa(1:8:end),'^','MarkerSize',10,'LineWidth',2,'Color',[0 0 0]/255,'MarkerFaceColor',[0 0 0]/255)
plot(xlim,[0 0],'-','Color',[0 0 0]/255,'LineWidth',2)


xlabel('Time from pulse (s)')
ylabel('Diff. proj. ch. axis')
set(gca,'FontSize',15);
box off
set(gca,'TickDir','out')
limite=1.2079;
ylim([-limite/5 limite])
xlim([0 0.65])
xlabel('Time (s)')
set(gca,'Fontsize',20,'TickDir','out','YTick',[])
box off
title('Population')




