clear
clc
close all


%script that plots behavior regression weights across all animals


load data/numsessions_all_rats
%%% (generated by number_sessions_per_rat.m)
rat_list=rats(find(numhits>=120000 & early_rat==0));


plot_type='difference';


for iii=1:length(rat_list)
    
    ratto=rat_list{iii};
    
    [d_shap(iii),f_shap(iii)] = plot_logistic_regression(ratto,'all_trials','slope',0,0,0);
   
end


%%% scatterplot

figure; 
plot(f_shap,d_shap,'.k','MarkerSize',50);
set(gca,'TickDir','out','FontSize',20);
box off;
xlabel('Index frequency');
ylabel('Index location')
axis equal
xlim([-.8 -.15]);
ylim([-.8 -.15]);





%%%% PLOT KERNELS FOR LOCATION EVIDENCE %%%%

h_loc3=figure;
set(h_loc3,'Position',[437    247         545         115]);

%%% this defines the subplots
ha_loc3 = tight_subplot(1,4,0.05);

h_freq3=figure;
set(h_freq3,'Position',[1140         247         545         115]);

%%% this defines the subplots
ha_freq3 = tight_subplot(1,4,0.05);



example_rats_location=[11 5 15 19];

example_rats_frequency=[3 18 1 26];



for i=1:4
    
    

    ratto=rats{example_rats_location(i)};


    %%% choose location subplot
    axes(ha_loc3(i));
    

    plot_errorbars=1;
    plot_markers=1;
    plot_logistic_regression(ratto,'all_trials','slope',1,'location',plot_type,plot_errorbars,plot_markers);

    


    ratto=rats{example_rats_frequency(i)};
    
    
    %%% choose frequency subplot
    axes(ha_freq3(i));
    

    plot_errorbars=1;
    plot_markers=1;
    plot_logistic_regression(ratto,'all_trials','slope',1,'frequency',plot_type,plot_errorbars,plot_markers);

    
    
end





