clear
clc

load('data/combined_kernels_per_context.mat')
%%% (generated by combine_neural_kernels_per_context.m)

data1=data_all_trials_loc;
data2=data_all_trials_freq;

resolution=glm.res*100;

data1.centers=-1:resolution/100:2;
data1.vecx=0.01:glm.res:glm.pulsedur;

data2.centers=-1:resolution/100:2;
data2.vecx=0.01:glm.res:glm.pulsedur;



wchall_all1=data1.glm_choice;
wchall_all2=data2.glm_choice;



wchall_all1=wchall_all1(51:end,:);
wchall_all2=wchall_all2(51:end,:);
data1.centers=data1.centers(51:end);
data2.centers=data2.centers(51:end);







%remove nans
a1=mean(wchall_all1,1);
a2=mean(wchall_all2,1);

good=find(~isnan(a1) & ~isnan(a2));

wchall_all1=wchall_all1(:,good);
wchall_all2=wchall_all2(:,good);



cc_all1=pca(wchall_all1(1:66,:));
cc_all1=cc_all1(:,1);
cc_all2=pca(wchall_all2(1:66,:));
cc_all2=cc_all2(:,1);






timepoints=data1.centers;

ind=find(timepoints>0 & timepoints<1.3);





wchall_all1=wchall_all1/norm(wchall_all1);
wchall_all2=wchall_all2/norm(wchall_all2);

cc_all=pca([wchall_all1; wchall_all2]);
cc_all=cc_all(:,1:3);
sc_all1=(wchall_all1-mean(wchall_all1))*cc_all;
sc_all2=(wchall_all2-mean(wchall_all2))*cc_all;



sc_all1=sc_all1-repmat(sc_all1(1,:),[101,1]);
sc_all2=sc_all2-repmat(sc_all2(1,:),[101,1]);













figure

subplot(1,2,1)
hold on
plot3(sc_all1(:,1),sc_all1(:,2),sc_all1(:,3),'Color',[162 0 148]/255,'LineWidth',2);

plot3(-sc_all1(:,1),-sc_all1(:,2),-sc_all1(:,3),'Color',[162 0 148]/255,'LineWidth',2);
    

plot3(sc_all1(1,1),sc_all1(1,2),sc_all1(1,3),'.','Color',[162 0 148]/255,'MarkerSize',20);

plot3(sc_all1(66,1),sc_all1(66,2),sc_all1(66,3),'.','Color',[162 0 148]/255,'MarkerSize',20);
plot3(-sc_all1(66,1),-sc_all1(66,2),-sc_all1(66,3),'.','Color',[162 0 148]/255,'MarkerSize',20);


point=cc_all1'*cc_all/5;
plot3([-point(1) point(1)],[-point(2) point(2)],[-point(3) point(3)],'Color',[162 0 148]/255,'LineWidth',3);


set(gca,'FontSize',20)
xlabel('PC 1')
ylabel('PC 2')
set(gca,'XTick',[],'YTick',[])

box off
set(gca,'TickDir','out')
axis equal







subplot(1,2,2)


hold on
plot3(sc_all2(:,1),sc_all2(:,2),sc_all2(:,3),'Color',[162 0 148]/255,'LineWidth',2);

plot3(-sc_all2(:,1),-sc_all2(:,2),-sc_all2(:,3),'Color',[162 0 148]/255,'LineWidth',2);
    

plot3(sc_all2(1,1),sc_all2(1,2),sc_all2(1,3),'.','Color',[162 0 148]/255,'MarkerSize',20);

plot3(sc_all2(66,1),sc_all2(66,2),sc_all2(66,3),'.','Color',[162 0 148]/255,'MarkerSize',20);
plot3(-sc_all2(66,1),-sc_all2(66,2),-sc_all2(66,3),'.','Color',[162 0 148]/255,'MarkerSize',20);


point=cc_all2'*cc_all/5;
plot3([-point(1) point(1)],[-point(2) point(2)],[-point(3) point(3)],'Color',[162 0 148]/255,'LineWidth',3);


set(gca,'FontSize',20)
xlabel('PC 1')
ylabel('PC 2')
set(gca,'XTick',[],'YTick',[])

box off
set(gca,'TickDir','out')
axis equal




