clear
clc
close all


%%% This script plots the psychometric curves across all rats


%%% find rats with at least 120000 trials (generated by
%%% number_sessions_per_rat.m)
load('data/numsessions_all_rats.mat');
rat_list=rats(find(numhits>=120000));




%%% load psychometrics data (generated by save_psychometrics.m)
load('data/psychometrics_all_rats.mat');
rats_psychometrics=rats;






h=figure;
set(h,'Position',[616   458   477   560]);


for i=1:length(rat_list)
    
    %select the psychometrics data for the current rat

    rat_index=find(ismember(rats_psychometrics,rat_list{i}));
    
    cdir=cdirs{rat_index};
    cfreq=cfreqs{rat_index};
    cdir_num=cdir_nums{rat_index};
    cfreq_num=cfreq_nums{rat_index};
    
    
    vec=[-4 -2.5 -1 1 2.5 4];
    
    le1=cdir;
    le2=cfreq;
    



    %%% location context, ranked by location strengths
    subplot(2,2,1)
    hold on
    y1=nanmean(le1,1);
    ylim([0 1])
    xlim([-4 4])
    hold on
    if(i==1)
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    end
    set(gca,'XTick',vec)
    box off
    set(gca,'TickDir','out')
    set(gca,'FontSize',20);
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y1', ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'k','LineWidth',1)
    ylim([0 1])
    xlim([-4 4])
    hold on
    set(gca,'XTick',vec)
     

    %%% frequency context, ranked by location strengths
    subplot(2,2,3)
    hold on
    y3=nanmean(le2,1);
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y3', ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'k','LineWidth',1)
    ylim([0 1])
    xlim([-4 4])
    hold on
    set(gca,'XTick',vec)
    if(i==1)
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    end    
    box off
    set(gca,'TickDir','out')
    set(gca,'FontSize',20);
    
    
    

    %%% location context, ranked by frequency strengths
    subplot(2,2,2)
    hold on
    y2=nanmean(le1,2);
    ylim([0 1])
    xlim([-4 4])
    hold on
    if(i==1)
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    end
    set(gca,'XTick',vec)
    
    box off
    set(gca,'TickDir','out')
    set(gca,'FontSize',20);
    
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y2, ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'-b','LineWidth',1)
    ylim([0 1])
    xlim([-4 4])
    hold on
    set(gca,'XTick',vec)
    
    
    





    %%% frequency context, ranked by frequency strengths
    subplot(2,2,4)
    hold on    
    y4=nanmean(le2,2);
    ft = fittype( 'bao+t./(1+exp(-(x-alpha)/beta))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( ft );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0];
    opts.StartPoint = [0.5 0.5 1 1];
    opts.Upper = [0.1 2 15 15];
    [fitresult, gof] = fit( vec', y4, ft, opts );
    x=-4:.01:4;
    y=fitresult.bao+fitresult.t./(1+exp(-(x-fitresult.alpha)/fitresult.beta));
    hold on
    plot(x,y,'b','LineWidth',1)
    ylim([0 1])
    xlim([-4 4])
    hold on
    set(gca,'XTick',vec)
    if(i==1)
    plot([-4 4],[.5 .5],'k:','LineWidth',1)
    end    
    box off
    set(gca,'TickDir','out')
    set(gca,'FontSize',20);
    
    
    
    
    
    
end





