function [d_shap,f_shap,d_shap_se,f_shap_se] = get_neural_slope(rat_name)

rat=rat_name(2:end);
rat=str2double(rat);



res=2;
dur=66;


load data/combined_kernels.mat
%%% (generated by combine_neural_kernels.m)



data=data_all_trials;

data.centers=-1:res/100:2;

vecx=0.01:0.02:dur/100;
data.vecx=vecx;



load data/rat_for_each_neuron

ind=find(rat_numbers==rat);






wddall=data.glm_dd(:,ind);
wfdall=data.glm_fd(:,ind);
wdfall=data.glm_df(:,ind);
wffall=data.glm_ff(:,ind);
wchall=data.glm_choice(:,ind);



centers=data.centers;
vecx=data.vecx;

wchall_all=wchall;

[~,ind1]=min(abs(centers));
[~,ind2]=min(abs(centers-1.3));
indi=ind1:ind2;
wchall=wchall(indi,:);



[cc,sc,lc]=pca(wchall);


if(sign(wchall(end,:)*cc(:,1))<0)
    cc(:,1)=-cc(:,1);
end



wdall=(wddall+wdfall)/2;
wfall=(wfdall+wffall)/2;


[cd3,sd,ld]=pca(wdall);
[cf3,sf,lf]=pca(wfall);


d_ratio=norm(wdfall(end,:))/norm(wddall(end,:));

f_ratio=norm(wfdall(end,:))/norm(wffall(end,:));



wddall_orig=wddall;
wfdall_orig=wfdall;
wdfall_orig=wdfall;
wffall_orig=wffall;

wchall=[zeros(1,length(ind)); wchall];
wddall=[wddall;zeros(1,length(ind))];
wfdall=[wfdall;zeros(1,length(ind))];
wdfall=[wdfall;zeros(1,length(ind))];
wffall=[wffall;zeros(1,length(ind))];



    
    

d1=fliplr(cc(:,1)'*wddall_orig');
d2=fliplr(cc(:,1)'*wdfall_orig');

f1=fliplr(cc(:,1)'*wffall_orig');
f2=fliplr(cc(:,1)'*wfdall_orig');

    


x=vecx;
y=d1-d2;
y=y/max(abs(y));
pd=polyfit(x,y,1);
d_shap=pd(1);


x=vecx;
y=f1-f2;
y=y/max(abs(y));
pf=polyfit(x,y,1);
f_shap=pf(1);




load(['data/kernel_bootstrap_' rat_name '.mat'],'wddall_se','wfdall_se','wdfall_se','wffall_se');
%%% (generated by combine_neural_kernels.m)


for jjj=1:5




    d1=fliplr(cc(:,1)'*wddall_se(:,:,jjj)');
    d2=fliplr(cc(:,1)'*wdfall_se(:,:,jjj)');

    f1=fliplr(cc(:,1)'*wffall_se(:,:,jjj)');
    f2=fliplr(cc(:,1)'*wfdall_se(:,:,jjj)');




    x=vecx;
    y=d1-d2;
    y=y/max(abs(y));
    pd=polyfit(x,y,1);
    d_shap_boot(jjj)=pd(1);


    x=vecx;
    y=f1-f2;
    y=y/max(abs(y));
    pf=polyfit(x,y,1);
    f_shap_boot(jjj)=pf(1);



end

d_shap_se=std(d_shap_boot);
f_shap_se=std(f_shap_boot);


