function [] = plot_neur_new(rat_name,type)

%%% plot pulse responses

rat=rat_name(2:end);
rat=str2double(rat);


res=2;
dur=66;


load data/combined_kernels.mat
%%% (generated by combine_neural_kernels.m)

data=data_all_trials;

data.centers=-1:res/100:2;

vecx=0.01:0.02:dur/100;
data.vecx=vecx;



load data/rat_for_each_neuron
ind=find(rat_numbers==rat);


wddall=data.glm_dd(:,ind);
wfdall=data.glm_fd(:,ind);
wdfall=data.glm_df(:,ind);
wffall=data.glm_ff(:,ind);
wchall=data.glm_choice(:,ind);



load(['data/kernel_bootstrap_' rat_name '.mat'],'wddall_se','wfdall_se','wdfall_se','wffall_se');
%%% (generated by combine_neural_kernels.m)

wddall_se=std(wddall_se,[],3);
wfdall_se=std(wfdall_se,[],3);
wdfall_se=std(wdfall_se,[],3);
wffall_se=std(wffall_se,[],3);




centers=data.centers;
vecx=data.vecx;

wchall_all=wchall;

[~,ind1]=min(abs(centers));
[~,ind2]=min(abs(centers-1.3));
indi=ind1:ind2;
wchall=wchall(indi,:);


[cc,sc,lc]=pca(wchall);


if(sign(wchall(end,:)*cc(:,1))<0)
    cc(:,1)=-cc(:,1);
end



wdall=(wddall+wdfall)/2;
wfall=(wfdall+wffall)/2;


[cd3,sd,ld]=pca(wdall);
[cf3,sf,lf]=pca(wfall);


wddall_orig=wddall;
wfdall_orig=wfdall;
wdfall_orig=wdfall;
wffall_orig=wffall;



d1=fliplr(cc(:,1)'*wddall_orig');
d2=fliplr(cc(:,1)'*wdfall_orig');

f1=fliplr(cc(:,1)'*wffall_orig');
f2=fliplr(cc(:,1)'*wfdall_orig');




x=vecx;
y=d1-d2;
y=y/max(abs(y));
pd=polyfit(x,y,1);
d_shap=pd(1);


x=vecx;
y=f1-f2;
y=y/max(abs(y));
pf=polyfit(x,y,1);
f_shap=pf(1);






if(strcmp(type,'location'))


    c=[cc(:,1) cd3(:,1) cd3(:,2)];

    a=wddall_orig';
    curve1=fliplr(c(:,1)'*a);
    a=wdfall_orig';
    curve2=fliplr(c(:,1)'*a);


    difa=curve1-curve2;
    maxval=max(abs(difa));
    difa=difa/maxval;


    hold on
    plot(vecx,difa,'-','MarkerSize',10,'LineWidth',2,'Color',[130 130 130]/255)


    plot(vecx,pd(1)*vecx+pd(2),'-','LineWidth',3,'Color',[130 130 130]/255)


    a_se=wddall_se.^2';
    curve1_se=abs(fliplr(c(:,1)'*a_se));
    a_se=wdfall_se.^2';
    curve2_se=abs(fliplr(c(:,1)'*a_se));

    media=difa;
    standa=sqrt((curve1_se+curve2_se)/2);
    standa=standa/maxval;
    vec1=media-standa;
    vec2=media+standa;
    fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
        [131 131 131]/255,'FaceAlpha',0.2,'EdgeColor','none');



    hold on

    plot(vecx(1:8:end),difa(1:8:end),'^','MarkerSize',10,'LineWidth',2,'Color',[130 130 130]/255,'MarkerFaceColor',[130 130 130]/255)

    plot(xlim,[0 0],'-','Color',[0 0 0]/255,'LineWidth',2)



    xlabel('Time from pulse (s)')
    ylabel('Diff. proj. ch. axis')
    set(gca,'FontSize',15);
    box off
    set(gca,'TickDir','out')





    ylimi=[-.2 1.45];
    ylim(ylimi)




elseif(strcmp(type,'frequency'))


    c=[cc(:,1) cf3(:,1) cf3(:,2)];

    hold on
    a=wffall_orig';
    curve1=fliplr(c(:,1)'*a);
    a=wfdall_orig';
    curve2=fliplr(c(:,1)'*a);

    difa=curve1-curve2;

    maxval=max(abs(difa));
    difa=difa/maxval;

    plot(vecx,difa,'-','MarkerSize',10,'LineWidth',2,'Color',[57 83 164]/255)
    plot(vecx,pf(1)*vecx+pf(2),'-','LineWidth',3,'Color',[57 83 164]/255)




    a_se=wffall_se.^2';
    curve1_se=abs(fliplr(c(:,1)'*a_se));
    a_se=wfdall_se.^2';
    curve2_se=abs(fliplr(c(:,1)'*a_se));


    media=difa;
    standa=sqrt((curve1_se+curve2_se)/2);
    standa=standa/maxval;
    vec1=media-standa;
    vec2=media+standa;
    fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
        [58 84 165]/255,'FaceAlpha',0.2,'EdgeColor','none');




    hold on
    plot(vecx(1:8:end),difa(1:8:end),'^','MarkerSize',10,'LineWidth',2,'Color',[57 83 164]/255,'MarkerFaceColor',[57 83 164]/255)
    plot(xlim,[0 0],'-','Color',[0 0 0]/255,'LineWidth',2)


    xlabel('Time from pulse (s)')
    ylabel('Diff. proj. ch. axis')
    set(gca,'FontSize',15);
    box off
    set(gca,'TickDir','out')



    ylimi=[-.2 1.45];

    ylim(ylimi)


end

