function [d_shap,f_shap] = plot_logistic_regression(ratto,dataset,index_type,plot_flag,feature_type,plot_type,plot_errorbars,plot_markers)

%%% plots and compute statistics of psych. kernels


%%% input arguments:

%%% ratto : e.g. 'P100'

%%% dataset : 'all_trials', 'half1', 'half2'

%%% index_type : 'slope', 'ratio'

%%% plot_flag : 0 , 1  <= whether to produce a plot or not

%%% feature_type: 'location' ,'frequency'

%%% plot_type: 'average', 'original', 'difference'

%%% plot_errorbars: 0,1

%%% plot_markers: 0,1


logreg_results=load(['data/logistic_regression_results/logreg_best_' ratto '_5.mat']);
%%% (generated by compute_logistic_regression_all_rats.m)


vecx=logreg_results.vecx;

if(strcmp(dataset,'all_trials'))
    
    thetadd=logreg_results.thetad(2:27);
    thetafd=logreg_results.thetad(28:end);
    thetadf=logreg_results.thetaf(2:27);
    thetaff=logreg_results.thetaf(28:end);
    
elseif(strcmp(dataset,'half1'))
    
    thetadd=logreg_results.thetad_half(2:27,1);
    thetafd=logreg_results.thetad_half(28:end,1);
    thetadf=logreg_results.thetaf_half(2:27,1);
    thetaff=logreg_results.thetaf_half(28:end,1);
    
elseif(strcmp(dataset,'half2'))
    
    thetadd=logreg_results.thetad_half(2:27,2);
    thetafd=logreg_results.thetad_half(28:end,2);
    thetadf=logreg_results.thetaf_half(2:27,2);
    thetaff=logreg_results.thetaf_half(28:end,2);
    
else
    error('use what?')
end



%%% d_shap,f_shap are returned by function and used to sort curves

%time x relevance
d(:,1)=thetadd;
d(:,2)=thetadf;

f(:,1)=thetaff;
f(:,2)=thetafd;



if(strcmp(index_type,'ratio'))

    %%% max difference across all time points
    d_max=max(d(:,1)-d(:,2)); %loc
    f_max=max(f(:,1)-f(:,2)); %frq

    %%% min difference across all time points
    d_min=min(d(:,1)-d(:,2)); %loc
    f_min=min(f(:,1)-f(:,2)); %frq


    %%% score assigned as the ratio between final difference and average difference
    d_shap=d_min/d_max;
    f_shap=f_min/f_max;

elseif(strcmp(index_type,'slope'))

    x=vecx;
    y=d(:,1)-d(:,2);
    y=y';
    y=y/max(abs(y));
    pd=polyfit(x,y,1);
    d_shap=pd(1);


    x=vecx;
    y=f(:,1)-f(:,2);
    y=y';
    y=y/max(abs(y));
    pf=polyfit(x,y,1);
    f_shap=pf(1);

else

    error('what index type?')
end



%%% if no need to plot, stop here
if(plot_flag==0)
    return
end



indices_markers=2:3:26;



thetadds=logreg_results.thetad_se(2:27);
thetafds=logreg_results.thetad_se(28:end);
thetadfs=logreg_results.thetaf_se(2:27);
thetaffs=logreg_results.thetaf_se(28:end);


%%% divide curves into the average and the difference
if(strcmp(plot_type,'average') || strcmp(plot_type,'difference'))
    mud=(thetadd+thetadf)./2;
    thetadd=thetadd-mud;
    thetadf=thetadf-mud;
    
    muf=(thetaff+thetafd)./2;
    thetaff=thetaff-muf;
    thetafd=thetafd-muf;
    
    
end






if(strcmp(feature_type,'location'))
    
    
    if(strcmp(plot_type,'average'))
        
        plot(vecx,mud,'-','MarkerSize',10,'LineWidth',1,'Color',[0 0 0])
        xlim([vecx(1) vecx(end)])
        ylim([0 5]/1000)
        
        
        
    elseif(strcmp(plot_type,'difference') || strcmp(plot_type,'original'))
        
        
        
        maxval=max(abs(thetadd));
        thetadd=thetadd/maxval;
        thetadf=thetadf/maxval;
        
        thetadds=thetadds/maxval;
        thetadfs=thetadfs/maxval;
        
        
        
        
        hold on
        if(plot_errorbars)
            vec1=thetadd'-thetadds';
            vec2=thetadd'+thetadds';
            fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
                [130 130 130]/255,'FaceAlpha',0.2,'EdgeColor',[130 130 130]/255);
        end
        plot(vecx,thetadd,'-','MarkerSize',10,'LineWidth',1,'Color',[130 130 130]/255)
        if(plot_markers)
            plot(vecx(indices_markers),thetadd(indices_markers),'.','MarkerSize',30,'LineWidth',1,'Color',[130 130 130]/255)
        end
        
        
        if(plot_errorbars)
            vec1=thetadf'-thetadfs';
            vec2=thetadf'+thetadfs';
            fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
                [130 130 130]/255,'FaceAlpha',0.2,'EdgeColor',[130 130 130]/255);
        end
        plot(vecx,thetadf,'-','MarkerSize',10,'LineWidth',1,'Color',[130 130 130]/255)
        if(plot_markers)
            plot(vecx(indices_markers),thetadf(indices_markers),'.','MarkerSize',30,'LineWidth',1,'Color',[130 130 130]/255)
        end
            
        xlim([vecx(1) vecx(end)])
        
        
        set(gca,'XTick',vecx([1 length(vecx)]));
        set(gca,'XTickLabel',[0 1.3]);
        set(gca,'FontSize',15);
        box off
        set(gca,'TickDir','out')
        
        plot(xlim,[0 0],'k--')
        
    else
        
        error('wrong plot type')
        
    end
    
    
    
    
    
    
elseif(strcmp(feature_type,'frequency'))
    
    
    
    if(strcmp(plot_type,'average'))
        
        
        plot(vecx,muf,'-','MarkerSize',10,'LineWidth',1,'Color',[0 0 1])
        
        xlim([vecx(1) vecx(end)])
        ylim([0 5]/1000)
        
        
        
        
    elseif(strcmp(plot_type,'difference') || strcmp(plot_type,'original'))
        
        
        maxval=max(abs(thetaff));
        thetaff=thetaff/maxval;
        thetafd=thetafd/maxval;
        
        thetaffs=thetaffs/maxval;
        thetafds=thetafds/maxval;
        
        
        
        hold on
        if(plot_errorbars)
            vec1=thetaff'-thetaffs';
            vec2=thetaff'+thetaffs';
            fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
                [57 83 164]/255,'FaceAlpha',0.2,'EdgeColor',[57 83 164]/255);
        end
        plot(vecx,thetaff,'-','MarkerSize',10,'LineWidth',1,'Color',[57 83 164]/255)
        if(plot_markers)
            plot(vecx(indices_markers),thetaff(indices_markers),'.','MarkerSize',30,'LineWidth',1,'Color',[57 83 164]/255)
        end
        
        
        if(plot_errorbars)
            vec1=thetafd'-thetafds';
            vec2=thetafd'+thetafds';
            fill([vecx vecx(end:-1:1) vecx(1)],[vec1 vec2(end:-1:1) vec1(1)],...
                [57 83 164]/255,'FaceAlpha',0.2,'EdgeColor',[57 83 164]/255);
        end
        plot(vecx,thetafd,'-','MarkerSize',10,'LineWidth',1,'Color',[57 83 164]/255)
        if(plot_markers)
            plot(vecx(indices_markers),thetafd(indices_markers),'.','MarkerSize',30,'LineWidth',1,'Color',[57 83 164]/255)
        end
        xlim([vecx(1) vecx(end)])
        
        
        set(gca,'FontSize',15);
        box off
        set(gca,'TickDir','out')
        set(gca,'XTick',vecx([1 length(vecx)]));
        set(gca,'XTickLabel',[0 1.3]);
        
        
        plot(xlim,[0 0],'k--')
        
    end
    
else
    error('wrong feature type');
end








